### ISSUE TITLE
Add library to pack's data collection

### ISSUE THREAD

**Issue by stefan-hoeck** [MarcelineVQ/idris2-newtype-deriving#1]
Hi

I'm not sure whether you are on the Idris discord, so I ask this here.

I like the idea of this library a lot (obviously). Would you mind if I added this to [pack's](https://github.com/stefan-hoeck/idris2-pack) package collection? You can see the current list of packages [here](https://github.com/stefan-hoeck/idris2-pack-db/blob/main/STATUS.md).

Cheers

Stefan

**Comment by MarcelineVQ** [comment]
I replied to this via email but I'm not sure if that sends you the reply directly or what all it does exactly since I'm not sure I've ever done that before, so just in case I'll repeat it here:

Hey neat timing, I just started using pack today! I'd like to be on the discord but I just have no time for chats these days :D

Absolutely you can add this, and there's still a lot I want to do with it that's been similarly stunted by lack of time, deriving Functor/Applicative/Monad in particular

**Comment by stefan-hoeck** [comment]
I'm afraid your email didn't reach me. :-)

I'll add this to the package collection then. If all goes well, it should be included in tomorrow's nightly. Feel free to add other libraries of yours to pack. Just submit a PR to [pack-db](https://github.com/stefan-hoeck/idris2-pack-db/).

**Comment by stefan-hoeck** [comment]
It worked! I'll close this then.
